### ISSUE TITLE
Support for Kodi 18 Leia?

### ISSUE THREAD

**Issue by regisfrias** [aajanki/plugin.video.yleareena.jade#3]
Hi,

thanks for the work on this!

I was wondering how much trouble would it be to add support for Kodi 18. It still seems to be a thing in many places. For example I'm using Raspberry Pi OS and the latest version on that repo is 18: https://kodi.wiki/view/HOW-TO:Install_Kodi_on_Raspberry_Pi#Raspberry_Pi_OS

Also thanks for `yle-dl`! I use it almost every day :)

**Comment by aajanki** [comment]
The major problem with supporting Kodi 18 is that the Inputstream Adaptive plugin for Kodi 18 (the plugin that actually takes care of streaming the video) doesn't properly support the Areena video format (MPEG DASH). One would need to backport fixes from the latest Inputstream version to Kodi 18.

If a suitable version of Inputstream Adaptive is one day released, modifying this plugin to support Kodi 18 should be relative easy, but I don't want to spend effort on that unless there first exists an Inputstream Adaptive version that supports Areena streams.

**Comment by regisfrias** [comment]
Thanks!
