### ISSUE TITLE
[Function Request] Added X-Forwarded-For header

### ISSUE THREAD

**Issue by Liqianyu** [aajanki/plugin.video.yleareena.jade#4]
The Playing URL returns a 404, but I think this is due to geo-blocking.

Is it possible to implement the X-Forwarded-For header functionality implemented in [yle-dl](https://github.com/aajanki/yle-dl/pull/283/)?

**Comment by aajanki** [comment]
I added the X-Forwarded-For header but can't test it easily. Can you see if it works and report back? The change is available in the master branch.

**Comment by aajanki** [comment]
I'm assuming that this is working now and closing this issue. Please re-open if  geo-blocking is still causing problems.
